/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mao_myffmpeg_FFMPEG */

#ifndef _Included_com_mao_myffmpeg_FFMPEG
#define _Included_com_mao_myffmpeg_FFMPEG
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mao_myffmpeg_FFMPEG
 * Method:    getRotation
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mao_myffmpeg_FFMPEG_getRotation
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
